### ISSUE TITLE
UML diagram

### ISSUE THREAD

**Issue by EliasVerstappe** [Projectwerk2-2018/Firmware#2]
What is the full description of the project? what is the application supposed to do?
I don't understand why some classes exist? The UML diagram is incomplete/incorrect.

I tried to make a new UML but can't figure out how to finish it.

Original UML:
![uml](https://user-images.githubusercontent.com/22295482/38679229-8915f36e-3e63-11e8-8b01-987da3ab975e.png)

New UML:
![newuml](https://user-images.githubusercontent.com/22295482/38679655-8ff19e1c-3e64-11e8-84ac-a4102b42b7da.jpg)

**Comment by VerEeckeDaan** [comment]
I'll explain the original UML.
1) The classes PIR_Sensor, Temperature and Humidity are classes with only one method, they just get the values from the sensors.
2) The class Si7013 is the library for the temp. and humiditysensor.
3) EnvironementSensorBoard is the "central" class of the program, it connects the input with the output. As input it has the sensorvalues, and on the output it makes sure that the class transciever is able to send something.
4) Sensordata gets three sensorvalues as input and makes from these 3 separate values one object.
5) if the mbed system reboots, the environementApp uses the start method to make sure everything is initialized as it should be.
6) Transceiver is a ABSTRACT class with only one method, send. This makes it easy to make different transceivers, not every transceivers send method is the same but it looks verry similar. There are two transceivers, the loratransceiver and lorawan.
7) The sensorDataByteSerializer puts all the data in the right form so the loratransceiver class will be able to send en receive data.

**Comment by EliasVerstappe** [comment]
Some extra questions:

(3) 
> ... on the output it makes sure that the class transciever is able to send something.

What is this "something" that will be sent? Sent where?
Also what does the `update()` do?

`loraTransceiver` will send the data it collects from `sensorDataByteSerializer`. 

(4)
> Sensordata gets three sensorvalues as input and makes from these 3 separate values one object.

"One object"; in what format? JSON? Something completely different?

**Comment by VerEeckeDaan** [comment]
(4)

> "One object"; in what format? JSON? Something completely different?

That one object bundles the three sensordata values but we haven't yet agreed how it should be represented.

(3)

> What is this "something" that will be sent? Sent where?

"something" is the data that wil be put up so the lorawan (who is a class "transciever") can send this data to the things netwerk.

> Also what does the update() do?

This method ensures that the program reads the values of the sensor every on advance agreed time intervals
